import React, {Fragment} from 'react';
import Header from '../layout/header';
import { Footer } from '../layout/footer';
import { SectionTitle } from '../content/element/section-title';
import { connect } from 'react-redux';

const Terms = (props) => {
    const light = props.logo[0].light;
    return (
        <Fragment>
            {/* Header section start */}
            <section className="header-breadcrumb bgimage overlay overlay--dark">
                <div className="mainmenu-wrapper">
                    <Header logo={light} class="menu--light" />
                </div>
                {/* <!-- ends: .mainmenu-wrapper --> */}
            </section>
            {/* Header section end */}

            <section className="faq-wrapper section-padding border-bottom">
                <div className="container">
                    <SectionTitle
                    title="Terms of Service"
                    content="" />

                    <div className="row">
                        <div className="col-lg-12">
                          <p className="font-weight-bold">Last Updated: 12/26/2019</p>

                          <p>Thank you for using Homebase!</p>
                          <p>Homebase (&ldquo;Homebase,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;) provides its services (described below) to you through its website located at http://www.renthomebase.com (the &ldquo;Site&rdquo;) (such services, including any new features and applications, and the Site, collectively, the &ldquo;Service(s)&rdquo;), subject to the following Terms of Service (as amended from time to time, these &ldquo;Terms of Service&rdquo;, including all policies, agreements and other documents incorporated by reference into these Terms of Service and each Member Agreement (as defined in Section 3.1 below)). These Terms of Service and each Member Agreement are collectively referred to as this &ldquo;Agreement.&rdquo;</p>
                          <p>Homebase reserves the right to modify these Terms of Service at any time in accordance with this provision. If we make changes to these Terms of Service, we will post the revised Terms of Service on the Site and update the &ldquo;Last Updated&rdquo; date at the top of these Terms of Service. We will also provide you with notice of the modifications by email at least thirty (30) days before the date they become effective. If you disagree with the revised Terms of Service, you may terminate this Agreement with immediate effect. We will inform you about your right to terminate the Agreement in the notification email. If you do not terminate your Agreement before the date the revised Terms of Service become effective, your continued access to or use of the Services will constitute acceptance of the revised Terms of Service.</p>
                          <p>PLEASE READ THESE TERMS OF SERVICE CAREFULLY, AS THEY CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS. THE AGREEMENT TO ARBITRATE REQUIRES (WITH LIMITED EXCEPTION) THAT YOU SUBMIT CLAIMS YOU HAVE AGAINST US TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST Homebase ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, (2) YOU WILL ONLY BE PERMITTED TO SEEK RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ON AN INDIVIDUAL BASIS, AND (3) YOU MAY NOT BE ABLE TO HAVE ANY CLAIMS YOU HAVE AGAINST US RESOLVED BY A JURY OR IN A COURT OF LAW.</p>
                          <p>In addition, when using certain services, you will be subject to any additional terms applicable to such services that may be posted on the Service from time to time, including, without limitation, the Privacy Policy located at http://www.renthomebase.com/privacy (the &ldquo;Privacy Policy&rdquo;) and the Member Agreement. All such terms are hereby incorporated by reference into these Terms of Service.</p>

                          <br />
                          <h3>1. Scope of Homebase Services</h3>
                          <br />

                          <p>1.1 The Service is designed to make available flexible occupancy accommodations of furnished residential apartment units (each a &ldquo;Unit,&rdquo; and the building in which such Unit is located may be referred to as the &ldquo;Building&rdquo;) in multi-family apartment properties (&ldquo;Accommodations&rdquo;) for its registered users (&ldquo;Members&rdquo;) on the terms and conditions provided in this Agreement.
                              <br /> 1.2 The Service may provide, or third parties may provide, links or other access to other sites and resources on the Internet. Homebase has no control over such sites and resources and Homebase is not responsible for and does not endorse such sites and resources. You further acknowledge and agree that Homebase will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site or resource. Any dealings you have with third parties found while using the Service are between you and the third party, and you agree that Homebase is not liable for any loss or claim that you may have against any such third party.
                              <br /> 1.3 Due to the nature of the Internet, Homebase cannot guarantee the continuous and uninterrupted availability and accessibility of the Services. Homebase may restrict the availability of the Services or certain areas or features thereof, if this is necessary in view of capacity limits, the security or integrity of our servers, or to carry out maintenance measures that ensure the proper or improved functioning of the Services. Homebase may improve, enhance and modify the Services and introduce new Homebase Services from time to time. Homebase reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Homebase will not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>

                          <br />
                          <h3>2. Account Registration, Eligibility, Member Verification</h3>
                          <br />

                          <p>2.1 You must register for an account ("Homebase Account") to access and use the Services. If you are registering an Homebase Account for a business, organization or other legal entity, you represent and warrant that you have the authority to legally bind that entity and grant us all permissions and licenses provided in this Agreement. In addition, references herein to &ldquo;you&rdquo; and &ldquo;your&rdquo; will mean, collectively, you and such legal entity. You warrant that all statements in your rental application and other documents submitted by you to us (whether previously or in the future) are accurate. If they are not, this will be a non-curable breach of the Member Agreement and we may terminate your rights under the Member Agreement.
                              <br /> 2.2 If you are a legal entity, you will be responsible for the actions of any individual who uses the Services under your account. In addition, if an individual using the Services under your account violates this Agreement, you (as the responsible legal entity) will be deemed the breaching party under this Agreement.
                              <br /> 2.2 In order to access and use the Services or register a Homebase Account you must be an individual at least 18 years old or a duly organized, validly existing business, organization or other legal entity in good standing under the laws of the country you are established and able to enter into legally binding contracts.
                              <br /> 2.3 You can register a Homebase Account using an email address and creating a password, or through your account with certain third-party social networking services, such as Facebook or Google ("SNS Account"). You have the ability to disable the connection between your Homebase Account and your SNS Account at any time.
                              <br /> 2.4 You agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Service&rsquo;s registration form and each Member Agreement. If your information is not true, accurate, current, or complete, this will be a non-curable material breach of this Agreement and we may terminate your rights under this Agreement and all applicable Member Agreements. Registration data and certain other information about you are governed by our Privacy Policy.
                              <br /> 2.5 You may not register more than one (1) Homebase Account unless Homebase authorizes you to do so. You may not assign or otherwise transfer your Homebase Account to another party.
                              <br /> 2.6 You are responsible for maintaining the confidentiality of your password and account, if any, and are fully responsible for any and all activities that occur under your password or account. You agree to (a) immediately notify Homebase of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session when accessing the Service. Homebase will not be liable for any loss or damage arising from your failure to comply with this Section.
                              <br /> 2.8 You acknowledge that Homebase may establish general practices and limits concerning use of the Service, including without limitation the maximum period of time that data or other content will be retained by the Service and the maximum storage space that will be allotted on Homebase&rsquo;s servers on your behalf. You agree that Homebase has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Service. You acknowledge that Homebase reserves the right to terminate accounts that are inactive for an extended period of time. You further acknowledge that Homebase reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</p>

                          <br />
                          <h3>3. Financial Terms for Guests</h3>
                          <br />

                          <p>3.1 Homebase is responsible for honoring any confirmed bookings and making available any Accommodations reserved through the Services. If you choose to enter into a transaction with Homebase for the booking of an Accommodation (Members who book Accommodations are &ldquo;Guests&rdquo;), you agree and understand that you will be required to enter into a Member Agreement with Homebase (a &ldquo;Member Agreement&rdquo;) for the Accommodation for the Unit and you agree to accept any terms, conditions, rules and restrictions associated with such Accommodation imposed by Homebase, including the Homebase Guest Rules and Regulations Policy displayed from time to time on the Site. You agree to pay Homebase for all applicable fees (&ldquo;Service Fees&rdquo;) for any booking requested in connection with your Homebase Account and more particularly identified in the Member Agreement. In the event of a conflict between any term in the Member Agreement and any term in this Agreement, the terms in the Member Agreement will apply for the applicable accommodation. Please note that Homebase cannot control any fees that may be charged to a Guest by his or her bank related to Homebase&rsquo;s collection of the Service Fees, and Homebase disclaims all liability in this regard.
                              <br /> 3.2 In connection with your requested booking, you will be asked to provide customary billing information such as name, billing address and credit card information either to Homebase or its third party payment processor. You agree to pay Homebase for any confirmed bookings made in connection with your Homebase Account in accordance with this Agreement by one of the methods described on the Site &ndash; e.g. by credit card. You hereby authorize the collection of such amounts by charging the credit card provided as part of requesting the booking, either directly by Homebase or indirectly, via a third party online payment processor or by one of the payment methods described on the Site. You also authorize Homebase to charge your credit card in the event of damage caused at an Accommodation as contemplated under &ldquo;Damage to Accommodations&rdquo; below and for other costs and fees associated with the Accommodation or any Booking Modifications, including cleaning charges, late fees and interest, taxes and other costs identified in these Terms of Service or in the Member Agreement. If you are directed to Homebase&rsquo;s third party payment processor, you may be subject to terms and conditions governing use of that third party&rsquo;s service and that third party&rsquo;s personal information collection practices. Please review such terms and conditions and privacy policy before using the services. Once your confirmed booking transaction is complete you will receive a confirmation email summarizing your confirmed booking.
                              <br /> 3.3 You will be obligated to pay to us the Late Charge specified in the Member Agreement if you fail to pay any amount due in connection with the Accommodation within the time specified in the Member Agreement. You agree it would be impractical or extremely difficult to fix the actual damage to us and that the Late Charge is a reasonable estimate of the actual damages that the parties reasonably believe would occur as a result of late payment. In addition to the Late Charge, interest will accrue on any unpaid amount at the rate of ten percent (10%) per year beginning on the date on which the delinquent amount was due. Late Charges and interest due are in addition to, and not in lieu of, our other remedies under this Agreement, or otherwise at law or in equity.</p>

                          <br />
                          <h3>4. Booking Accommodations</h3>
                          <br />

                          <p>4.1 You understand that a confirmed booking of an Accommodation is a limited, revocable occupancy right granted to you by Homebase to enter, occupy and use the Unit for the duration of your stay, during which time a representative of Homebase (only where and to the extent permitted by applicable law) retains the right to re-enter the Unit. If indicated in the Member Agreement for the Unit, the term of the Accommodation may be extended or earlier terminated only in accordance with the terms set forth in the Member Agreement. The booking of an Accommodation is expressly subject to (i) your payment of the amounts designed in the Member Agreement as &ldquo;Initial Amounts Due&rdquo; before the specified date, and (ii) our receipt of a credit and background checks for all Guests of the Unit reasonably acceptable to us. If the foregoing conditions are not satisfied, we may rescind and cancel the booking of the Accommodation and the applicable Member Agreement and retain any portion of the Service Fees you have paid (if any) necessary to compensate us for the rescission of the Accommodation and Member Agreement, including any processing fee described in Section 5 below.
                              <br /> 4.2 You agree to leave the Unit no later than the checkout time on the Termination Date that Homebase specifies in the Member Agreement or such other time as mutually agreed upon between you and Homebase. If you stay past the specified or agreed upon checkout time without Homebase&rsquo;s consent (&ldquo;Overstay&rdquo;), you no longer have a license to stay in the Unit and Homebase is entitled to make you leave in a manner consistent with applicable law. In addition, you agree to pay for each twenty-four (24) hour period (or any portion thereof) that you Overstay, an additional nightly fee of up to two (2) times the average nightly fee originally paid by you to cover the inconvenience suffered by Homebase, plus all applicable fees, taxes, and any legal expenses incurred by Homebase to make you leave (collectively, "Overstay Fees"). If you Overstay at a Unit, you authorize Homebase to charge you (and to charge your credit card) to collect Overstay Fees and any rental or occupancy taxes or similar charges assessed by any governmental or quasi-governmental authority due to the duration of your occupancy in the Unit.
                              <br /> 4.3 The Unit may be occupied only by the identified occupants specified in the Member Agreement for such Unit (you and the identified occupants, are referred to as &ldquo;Guests&rdquo; or &ldquo;Permitted Guests&rdquo;). You shall not permit occupancy of the Unit by more than the maximum occupancy identified in the Member Agreement. If you book an Accommodation on behalf of additional guests, you are required to ensure that every additional guest is made aware of and agrees to these Terms of Service and the applicable Member Agreement for the Unit. If you are booking for an additional guest who is a minor, you represent and warrant that you are legally authorized to act on behalf of the minor. If there is more than one Permitted Guest of the Unit, each Permitted Guest (other than minors for whom you are legally authorized to act on behalf of) is jointly and severally liable for all rental and other obligations. Violation of these Terms of Service or the applicable Member Agreement by any Permitted Guest is deemed a violation by all Permitted Guests. Any Permitted Guest who has permanently moved out according to another Permitted Guest may, at our option and discretion, no longer be entitled to occupancy of or keys to the Unit. However, the termination of that person's right of occupancy will not release that person from any and all obligations under this Agreement or any renewal, unless we agree otherwise in writing.
                              <br /> 4.4 You will expressly not be released from these Terms of Service or the Member Agreement for the Unit on the grounds of voluntary or involuntary school withdrawal or transfer, business transfer, layoff or termination, marriage, divorce, marriage reconciliation, loss of co-Residents, bad health, or any other reason unless we agree otherwise in writing. We may grant or withhold consent to a release in our sole discretion.</p>

                          <br />
                          <h3>5. Payment Processing</h3>
                          <br />

                          <p>5.1 You may choose to pay any portion of the Service Fees by (a) charging a credit card associated with your account or (b) debiting your bank account for purposes of automatic clearing house (&ldquo;ACH&rdquo;) payment. You will be charged a 2.9 percent (2.9%) processing fee each time you pay by credit card after the first month of your booking.
                              <br /> 5.2 All fees paid (a) by credit card will be charged to the credit card associated with your account with the applicable Payment Processor (defined below) and (b) from your bank account will be debited to the bank account that you provide to the applicable Payment Processor for purposes of ACH payment. Payment processing service for payment of the Service Fees will be provided by third party payment processers (collectively with any other payment processing service that Company makes available, the &ldquo;Payment Processors&rdquo;). Homebase currently uses Stripe (https://stripe.com/) as its Payment Processor, but reserves the right to change Payment Processors. You will render payment via the applicable Payment Processor. Service Fees will be processed by the applicable Payment Processor. You are bound by the applicable Payment Processor&rsquo;s terms and conditions for the processing of payments, as the same may be modified by such Payment Processor from time to time (collectively, the &ldquo;Payment Processer Terms&rdquo;). Information provided to any Payment Processor is governed by the applicable Payment Processor Terms. Stripe&rsquo;s Payment Processer Terms are comprised of Stripe&rsquo;s Terms of Service located at https://stripe.com/legal and Stripe&rsquo;s Privacy Policy located at https://stripe.com/privacy. We are not responsible for the performance of any Payment Processor, including Stripe.
                              <br /> 5.3 As a condition of Homebase enabling payment processing service through Stripe or any other Payment Processor, you agree to provide Homebase accurate and complete information about you and your business (if applicable) and to promptly update such information as needed, and also authorize Homebase to share such information and transaction information related to your use of the payment processing service provided by such Payment Processor. Homebase does not control any fees that may be charged to you by your bank related to Payment Processor&rsquo;s collection or disbursement of such payment, and Homebase disclaims all liability in this regard. You will ensure that you have sufficient funds or credit (as applicable) associated with the selected method of payment. You understand that the amounts charged or debited may vary and that this authorization will remain in effect until the expiration or termination of this Agreement. If an ACH payment is returned from the applicable bank account for insufficient or uncollected funds or for erroneous information, Homebase may reinitiate the returned ACH debit to the applicable bank account. Any amounts owed to Homebase that cannot be collected by ACH debit may be charged to any backup credit card on file for you. 5.4 By agreeing to this Agreement or continuing to use the Services, you authorize Homebase to electronically debit the account or charge the credit card you select for payment in the amount and upon the date you authorize, subject to the Payment Processor Terms, and if necessary, to electronically credit your account or credit card to correct erroneous debits or charges. You understand this authorization will remain in full force and effect until you notify Homebase by an email to hello@renthomebase.com that you revoke this authorization. You understand that Homebase requires at least three (3) business days&rsquo; prior notice of revocation of any payment authorization. You acknowledge that all payments that you authorize comply with all applicable law. Once you authorize payment, no changes or corrections to the payment may be made. You understand that you should retain a hard or electronic copy of your authorization for your records.</p>

                          <br />
                          <h3>6. Damage to Accommodations, Disputes between Members</h3>
                          <br />

                          <p>6.1 If you are a Guest, you are responsible for leaving the Unit in the condition it was in when you arrived. You acknowledge and agree that, as a Guest, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who you invite to, or otherwise provide access to, the Unit.
                              <br /> 6.2 In the event that Homebase claims otherwise and provides evidence of damage, including but not limited to, photographs, you agree to pay the cost of replacing the damaged items with equivalent items. After being notified of the claim and given forty eight (48) hours to respond, the payment will be charged to and taken from the credit card on file in your Homebase Account or from your bank account on file in your Homebase Account for purposes of ACH payment (according to the payment method you have previously selected). Homebase also reserves the right to charge the credit card or debit the bank account on file in your Homebase Account (as applicable), or otherwise collect payment from you and pursue any avenues available to Homebase in this regard, including using security deposits, in situations in which you have been determined, in Homebase&rsquo;s sole discretion, to have damaged any Unit, including, but not limited to, in relation to any payment requests made by Homebase, and in relation to any payments made by Homebase. If we are unable to charge the credit card or debit the bank account on file or otherwise collect payment from you, you agree to remit payment for any damage to the Unit to Homebase (if applicable).</p>

                          <br />
                          <h3>7. Member Content</h3>
                          <br />

                          <p>7.1 We may, in our sole discretion, permit Members to post, upload, publish, submit or transmit code, video, images, information, data, text, software, music, sound, photographs, graphics, messages (such content, &ldquo;Member Content&rdquo;). By making available any Member Content on or through the Services, you hereby grant to Homebase a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit such Member Content on, through, or by means of the Services. Homebase does not claim any ownership rights in any such Member Content and nothing in this Agreement will be deemed to restrict any rights that you may have to use and exploit any such Member Content.
                              <br /> 7.2 You acknowledge and agree that you are solely responsible for all Member Content that you make available through the Services. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available through the Services or you have all rights, licenses, consents and releases that are necessary to grant to Homebase the rights in such Member Content, as contemplated under this Agreement; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Homebase&rsquo;s use of the Member Content (or any portion thereof) on, through or by means of the Services will infringe, misappropriate or violate a third party&rsquo;s patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.
                              <br /> 7.3 You acknowledge and agree that Homebase may preserve content and may also disclose content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce this Agreement; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Homebase, its users and the public. You understand that the technical processing and transmission of the Service, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. 7.4 You will not post, upload, publish, submit or transmit any Member Content that: (i) is fraudulent, false, misleading (directly or by omission or failure to update information) or deceptive; (ii) is defamatory, libelous, obscene, pornographic, vulgar or offensive; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening or promotes violence or actions that are threatening to any other person or animal; (v) promotes illegal or harmful activities or substances; or (vi) violates any Homebase policy. Homebase may, without prior notice, remove or disable access to any Member Content that Homebase finds to be in violation of applicable law, this Agreement or Homebase&rsquo;s then-current policies or standards, or otherwise may be harmful or objectionable to Homebase, its Members, third parties, or property.
                              <br /> 7.5 Under no circumstances will Homebase be liable in any way for any content or materials of any third parties (including users), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. You acknowledge that Homebase does not pre-screen content, but that Homebase and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Service. Without limiting the foregoing, Homebase and its designees will have the right to remove any content that violates this Agreement or is deemed by Homebase, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content.</p>

                          <br />
                          <h3>8. Prohibited Activities</h3>
                          <br />

                          <p>8.1 You are solely responsible for all Member Content that you upload, post, publish or display (hereinafter, &ldquo;upload&rdquo;) or email or otherwise use via the Service. The following are examples of the kind of content and/or use that is illegal or prohibited by Homebase. Homebase reserves the right to investigate and take appropriate legal action against anyone who, in Homebase&rsquo;s sole discretion, violates this provision, including without limitation, removing the offending content from the Service, suspending or terminating the account of such violators and reporting you to the law enforcement authorities. You will not and will not assist or enable others to: </p>
                          <div>a) email or otherwise upload any Member Content that (i) infringes any intellectual property or other proprietary rights of any party; (ii) you do not have a right to upload under any law or under contractual or fiduciary relationships; (iii) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (iv) poses or creates a privacy or security risk to any person; (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, &ldquo;junk mail,&rdquo; &ldquo;spam,&rdquo; &ldquo;chain letters,&rdquo; &ldquo;pyramid schemes,&rdquo; &ldquo;contests,&rdquo; &ldquo;sweepstakes,&rdquo; or any other form of solicitation; (vi) is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another&rsquo;s privacy, hateful racially, ethnically or otherwise objectionable; or (vii) in the sole judgment of Homebase, is objectionable or which restricts or inhibits any other person from using or enjoying the Service, or which may expose Homebase or its users to any harm or liability of any type;
                              <br /> b) interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service; or
                              <br /> c) violate any applicable local, state, national or international law, or any regulations having the force of law;
                              <br /> d) impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;
                              <br /> e) solicit personal information from anyone under the age of 18;
                              <br /> f) copy, store or otherwise access or use any information, including personally identifiable information about any other Member, contained on the Site in any way that is inconsistent with Homebase&rsquo;s Privacy Policy or this Agreement or that otherwise violates the privacy rights of Members or third parties;
                              <br /> g) harvest or collect email addresses or other contact information of other users from the Service by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;
                              <br /> h) unless Homebase explicitly permits otherwise, book any Accommodation if you will not actually be staying at the Accommodation yourself;
                              <br /> i) advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized;
                              <br /> j)further or promote any criminal activity or enterprise or provide instructional information about illegal activities;
                              <br /> k) obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Service.
                              <br /> l) attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services;
                              <br /> m) take any action that damages or adversely affects, or could damage or adversely affect the performance or proper functioning of the Services;</div>
                          <p>
                              <br /> 8.2 You will not use, copy, adapt, modify, prepare derivative works of, distribute, license, sell, transfer, publicly display, publicly perform, transmit, broadcast or otherwise exploit the Services except to the extent you are the legal owner of certain Member Content or as expressly permitted in this Agreement. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Homebase or its licensors, except for the licenses and rights expressly granted in this Agreement.
                              <br /> 8.3 Unless otherwise expressly authorized herein or in the Service, you agree not to display, distribute, license, perform, publish, reproduce, duplicate, copy, create derivative works from, modify, sell, resell, exploit, transfer or upload for any commercial purposes, any portion of the Service, use of the Service, or access to the Service. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Homebase or its licensors, except for the licenses and rights expressly granted in this Agreement.
                              <br /> 8.4 You acknowledge that Homebase has no obligation to monitor the access to or use of the Services by any Member or to review, disable access to, or edit any Member Content, but has the right to do so to (i) operate, secure and improve the Services (including without limitation for fraud prevention, risk assessment, investigation and customer support purposes); (ii) ensure Members&rsquo; compliance with this Agreement; (iii) comply with applicable law or the order or requirement of a court, law enforcement or other administrative agency or governmental body; (iv) respond to Member Content that it determines is harmful or objectionable; or (v) as otherwise set forth in this Agreement. Members agree to cooperate with and assist Homebase in good faith, and to provide Homebase with such information and take such actions as may be reasonably requested by Homebase with respect to any investigation undertaken by Homebase or a representative of Homebase regarding the use or abuse of the Services.
                              <br /> 8.5 If you feel that any Member you interact with, whether online or in person, is acting or has acted inappropriately, including but not limited to anyone who (i) engages in offensive, violent or sexually inappropriate behavior, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to Homebase by contacting us with your police station and report number (if available). You agree that any report you make will not obligate us to take any action (beyond that required by law, if any). </p>

                          <br />
                          <h3>9. Intellectual Property Rights</h3>
                          <br />

                          <p>9.1 You acknowledge and agree that the Service may contain content or features (&ldquo;Service Content&rdquo;) that are protected by copyright, patent, trademark, trade secret or other proprietary rights and laws. Except as expressly authorized by Homebase, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Service Content, in whole or in part, except that the foregoing does not apply to your own Member Content that you legally upload to the Service. In connection with your use of the Service you will not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. If you are blocked by Homebase from accessing the Service (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address). Any use of the Service or the Service Content other than as specifically authorized herein is strictly prohibited. The technology and software underlying the Service or distributed in connection therewith are the property of Homebase, our affiliates and our partners (the &ldquo;Software&rdquo;). You agree not to copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Software. Any rights not expressly granted herein are reserved by Homebase.
                              <br /> 9.2 The Homebase name and logos are trademarks and service marks of Homebase (collectively the &ldquo;Homebase Trademarks&rdquo;). Other Homebase, product, and service names and logos used and displayed via the Service may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to Homebase. Nothing in this this Agreement should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of Homebase Trademarks displayed on the Service, without our prior written permission in each instance. All goodwill generated from the use of Homebase Trademarks will inure to our exclusive benefit.
                              <br /> 9.3 Homebase respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, you should notify Homebase of your infringement claim in accordance with the procedure set forth below.
                              <br /> 9.4 Homebase will process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act (&ldquo;DMCA&rdquo;) and other applicable intellectual property laws with respect to any alleged or actual infringement. A notification of claimed copyright infringement should be emailed to Homebase&rsquo;s Copyright Agent atcopyrightnotices@helloHomebase.com (Subject line: &ldquo;DMCA Takedown Request&rdquo;). You may also contact us by mail at 9 20th Street North Birmingham, AL 35203. </p>
                          <p>To be effective, the notification must be in writing and contain the following information:</p>
                          <ul>
                              <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
                              <li>a description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
                              <li>a description of where the material that you claim is infringing is located on the Service, with enough detail that we may find it on the Service;</li>
                              <li>your address, telephone number, and email address;</li>
                              <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;</li>
                              <li>a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner&rsquo;s behalf.</li>
                          </ul>
                          <p>9.5 If you believe that your Member Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner&rsquo;s agent, or pursuant to the law, to upload and use the content in your Member Content, you may send a written counter-notice containing the following information to the Copyright Agent: </p>
                          <ul>
                              <li>your physical or electronic signature;</li>
                              <li>identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;</li>
                              <li>a statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content; and</li>
                              <li>your name, address, telephone number, and email address, a statement that you consent to the jurisdiction of the federal court located within Alabama and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
                          </ul>
                          <p>If a counter-notice is received by the Copyright Agent, Homebase will send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion.</p>
                          <p>
                              <br /> 9.6 In accordance with the DMCA and other applicable law, Homebase has adopted a policy of terminating, in appropriate circumstances and at Homebase's sole discretion, users who are deemed to be repeat infringers. Homebase may also at its sole discretion limit access to the Service and/or terminate the memberships of any user.</p>

                          <br />
                          <h3>10. Social Networking Services</h3>
                          <br />

                          <p>10.1 You may enable or log in to the Service via various online third party services, such as social media and social networking services like Facebook or Twitter (&ldquo;Social Networking Services&rdquo;). By logging in or directly integrating these Social Networking Services into the Service, we make your online experiences richer and more personalized. To take advantage of this feature and capabilities, we may ask you to authenticate, register for or log into Social Networking Services on the websites of their respective providers. As part of such integration, the Social Networking Services will provide us with access to certain information that you have provided to such Social Networking Services, and we will use, store and disclose such information in accordance with our Privacy Policy. For more information about the implications of activating these Social Networking Services and Homebase&rsquo;s use, storage and disclosure of information related to you and your use of such services within Homebase (including your friend lists and the like), please see our Privacy Policy at www.Homebase.com/privacy. However, please remember that the manner in which Social Networking Services use, store and disclose your information is governed solely by the policies of such third parties, and Homebase shall have no liability or responsibility for the privacy practices or other actions of any third party site or service that may be enabled within the Service.
                              <br /> 10.2 In addition, Homebase is not responsible for the accuracy, availability or reliability of any information, content, goods, data, opinions, advice or statements made available in connection with Social Networking Services. As such, Homebase is not liable for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Social Networking Services. Homebase enables these features merely as a convenience and the integration or inclusion of such features does not imply an endorsement or recommendation.</p>

                          <br />
                          <h3>11. Indemnity and Release</h3>
                          <br />

                          <p>You agree to release, indemnify and hold Homebase and its affiliates and their officers, employees, directors and agents (collectively, &ldquo;Indemnitees&rdquo;) harmless from any from any and all losses, damages, expenses, including reasonable attorneys&rsquo; fees, rights, claims, actions of any kind and injury (including death) arising out of or relating to your use of the Service, any Member Content, your connection to the Service, your violation of this Agreement or your violation of any rights of another. Notwithstanding the foregoing, you will have no obligation to indemnify or hold harmless any Indemnitee from or against any liability, losses, damages or expenses incurred as a result of any action or inaction of such Indemnitee. If you are a California resident, you waive California Civil Code Section 1542, which says: &ldquo;A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.&rdquo; If you are a resident of another jurisdiction, you waive any comparable statute or doctrine.</p>

                          <br />
                          <h3>12. Disclaimer of Warranties</h3>
                          <br />

                          <p>YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. Homebase EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.
                              <br /> Homebase MAKES NO WARRANTY THAT (I) THE SERVICE WILL MEET YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.
                              <br /> IF YOU ARE BRINGING A MINOR AS AN ADDITIONAL GUEST, YOU ARE SOLELY RESPONSIBLE FOR THE SUPERVISION OF THAT MINOR THROUGHOUT THE DURATION OF YOUR STAY AND TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AGREE TO RELEASE AND HOLD HARMLESS Homebase FROM ALL LIABILITIES AND CLAIMS THAT ARISE IN ANY WAY FROM ANY INJURY, DEATH, LOSS OR HARM THAT OCCURS TO THAT MINOR DURING YOUR STAY OR IN ANY WAY RELATED TO YOUR STAY.</p>

                          <br />
                          <h3>13. Limitation of Liability</h3>
                          <br />

                          <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR ACCESS TO AND USE OF THE SERVICES OR ANY OTHER INTERACTION YOU HAVE WITH OTHER MEMBERS WHETHER IN PERSON OR ONLINE REMAINS WITH YOU.
                              <br /> YOU EXPRESSLY UNDERSTAND AND AGREE THAT Homebase WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA, DAMAGES FOR SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS OR OTHER INTANGIBLE LOSSES (EVEN IF Homebase HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM: (I) THESE TERMS; (II) THE BOOKING OF A LISTING; (III) THE USE OR THE INABILITY TO USE THE SERVICE; (IV) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (V) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (VI) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (VII) ANY OTHER MATTER RELATING TO THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Homebase HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
                              <br /> IN NO EVENT WILL Homebase&rsquo;S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OF ACTION ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT AND YOUR USE OF THE SERVICE INCLUDING, BUT NOT LIMITED TO, FROM YOUR BOOKING OF ANY LISTINGS VIA THE SERVICE, OR FROM THE USE OF OR INABILITY TO USE THE SERVICE AND IN CONNECTION WITH ANY ACCOMMODATION OR INTERACTIONS WITH ANY OTHER MEMBERS, EXCEED THE AMOUNT YOU HAVE PAID Homebase IN THE LAST SIX (6) MONTHS, OR, IF GREATER, ONE HUNDRED DOLLARS ($100).
                              <br /> THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Homebase AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OR EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU OR BE ENFORCEABLE WITH RESPECT TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE OR WITH THIS AGREEMENT, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.
                              <br /> IF YOU ARE A USER FROM NEW JERSEY, THE FOREGOING SECTIONS TITLED &ldquo;DISCLAIMER OF WARRANTIES&rdquo; AND &ldquo;LIMITATION OF LIABILITY&rdquo; ARE INTENDED TO BE ONLY AS BROAD AS IS PERMITTED UNDER THE LAWS OF THE STATE OF NEW JERSEY. IF ANY PORTION OF THESE SECTIONS IS HELD TO BE INVALID UNDER THE LAWS OF THE STATE OF NEW JERSEY, THE INVALIDITY OF SUCH PORTION SHALL NOT AFFECT THE VALIDITY OF THE REMAINING PORTIONS OF THE APPLICABLE SECTIONS.</p>

                          <br />
                          <h3>14. Dispute Resolution By Binding Arbitration: PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR RIGHTS.</h3>
                          <br />

                          <p>a) Agreement to Arbitrate This Dispute Resolution by Binding Arbitration section is referred to in this Terms of Service as the &ldquo;Arbitration Agreement.&rdquo; You agree that any and all disputes or claims that have arisen or may arise between you and Homebase, whether arising out of or relating to this Terms of Service (including any alleged breach thereof), the Services, any advertising, any aspect of the relationship or transactions between us, shall be resolved exclusively through final and binding arbitration, rather than a court, in accordance with the terms of this Arbitration Agreement, except that you may assert individual claims in small claims court, if your claims qualify. Further, this Arbitration Agreement does not preclude you from bringing issues to the attention of federal, state, or local agencies, and such agencies can, if the law allows, seek relief against us on your behalf. You agree that, by entering into this Terms of Service, you and Homebase are each waiving the right to a trial by jury or to participate in a class action. Your rights will be determined by a neutral arbitrator, not a judge or jury. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.
                              <br /> b) Prohibition of Class and Representative Actions and Non-Individualized Relief YOU AND Homebase AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH YOU AND Homebase AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON&rsquo;S OR PARTY&rsquo;S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY&rsquo;S INDIVIDUAL CLAIM(S), EXCEPT THAT YOU MAY PURSUE A CLAIM FOR AND THE ARBITRATOR MAY AWARD PUBLIC INJUNCTIVE RELIEF UNDER APPLICABLE LAW TO THE EXTENT REQUIRED FOR THE ENFORCEABILITY OF THIS PROVISION. </p>
                          <p>c) Pre-Arbitration Dispute Resolution Homebase is always interested in resolving disputes amicably and efficiently, and most customer concerns can be resolved quickly and to the customer&rsquo;s satisfaction by emailing customer support athello@renthomebase.com. If such efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute (&ldquo;Notice&rdquo;). The Notice to Homebase should be sent to 9 20th Street North, Birmingham, AL 35203 (&ldquo;Notice Address&rdquo;). The Notice must (i) describe the nature and basis of the claim or dispute and (ii) set forth the specific relief sought. If Homebase and you do not resolve the claim within sixty (60) calendar days after the Notice is received, you or Homebase may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by Homebase or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or Homebase is entitled. </p>
                          <p>d) Arbitration Procedures Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Association&rsquo;s (&ldquo;AAA&rdquo;) rules and procedures, including the AAA&rsquo;s Consumer Arbitration Rules (collectively, the &ldquo;AAA Rules&rdquo;), as modified by this Arbitration Agreement. For information on the AAA, please visit its website, http://www.adr.org. Information about the AAA Rules and fees for consumer disputes can be found at the AAA&rsquo;s consumer arbitration page, http://www.adr.org/consumer_arbitration. If there is any inconsistency between any term of the AAA Rules and any term of this Arbitration Agreement, the applicable terms of this Arbitration Agreement will control unless the arbitrator determines that the application of the inconsistent Arbitration Agreement terms would not result in a fundamentally fair arbitration. The arbitrator must also follow the provisions of these Terms of Service as a court would. All issues are for the arbitrator to decide, including, but not limited to, issues relating to the scope, enforceability, and arbitrability of this Arbitration Agreement. Although arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings, the arbitrator can award the same damages and relief on an individual basis that a court can award to an individual under the Terms of Service and applicable law. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.
                              <br /> Unless Homebase and you agree otherwise, any arbitration hearings will take place in a reasonably convenient location for both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, the determination shall be made by AAA. If your claim is for $10,000 or less, Homebase agrees that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules. If your claim exceeds $10,000, the right to a hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based. </p>
                          <p>e) Costs of Arbitration Payment of all filing, administration, and arbitrator fees (collectively, the &ldquo;Arbitration Fees&rdquo;) will be governed by the AAA Rules, unless otherwise provided in this Arbitration Agreement. If the value of the relief sought is $75,000 or less, at your request, Homebase will pay all Arbitration Fees. If the value of relief sought is more than $75,000 and you are able to demonstrate to the arbitrator that you are economically unable to pay your portion of the Arbitration Fees or if the arbitrator otherwise determines for any reason that you should not be required to pay your portion of the Arbitration Fees, Homebase will pay your portion of such fees. In addition, if you demonstrate to the arbitrator that the costs of arbitration will be prohibitive as compared to the costs of litigation, Homebase will pay as much of the Arbitration Fees as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive. Any payment of attorneys&rsquo; fees will be governed by the AAA Rules. </p>
                          <p>f) Confidentiality All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties. </p>
                          <p>g) Severability If a court or the arbitrator decides that any term or provision of this Arbitration Agreement (other than the subsection (b) titled &ldquo;Prohibition of Class and Representative Actions and Non-Individualized Relief&rdquo; above) is invalid or unenforceable, the parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement shall be enforceable as so modified. If a court or the arbitrator decides that any of the provisions of subsection (b) above titled &ldquo;Prohibition of Class and Representative Actions and Non-Individualized Relief&rdquo; are invalid or unenforceable, then the entirety of this Arbitration Agreement shall be null and void, unless such provisions are deemed to be invalid or unenforceable solely with respect to claims for public injunctive relief. The remainder of the Terms of Service will continue to apply. </p>
                          <p>h) Future Changes to Arbitration Agreement Not withstanding any provision in this Terms of Service to the contrary, Homebase agrees that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while you are a user of the Services, you may reject any such change by sending Homebase written notice within thirty (30) calendar days of the change to the Notice Address provided above. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).</p>

                          <br />

                          <h3>15. Termination</h3>
                          <br />

                          <p>15.1 This Agreement shall be effective for a 30-day term, at the end of which it will automatically and continuously renew for subsequent 30-day terms until such time when you or Homebase terminate the Agreement in accordance with this provision.
                              <br /> 15.2 You may terminate this Agreement at any time by sending us an email. If a notice pursuant to this Section 16.2 or Section 16.3 is provided when a Member Agreement is in effect, the effective termination of this Agreement will not occur until the expiration of or earlier termination of such Member Agreement.
                              <br /> 15.3 Without limiting our rights specified below, Homebase may terminate this Agreement for convenience at any time by giving you thirty (30) days' notice via email to your registered email address.
                              <br /> 15.4 If no Member Agreement is in place at the time, Homebase may immediately, without notice, terminate this Agreement and/or stop providing access to the Services if (i) you have materially breached your obligations under these Terms of Service, the Member Agreement our policies or standards, (ii) you have violated applicable laws, regulations or third party rights, or (iii) Homebase believes in good faith that such action is reasonably necessary to protect the personal safety or property of Homebase, its Members, or third parties (for example in the case of fraudulent behavior of a Member).
                              <br /> 15.5 Refunds upon termination are governed in Section 5.2 of these Terms of Service.
                              <br /> 15.6 n addition, Homebase may take any of the following measures (i) to comply with applicable law, or the order or request of a court, law enforcement or other administrative agency or governmental body, or if (ii) you have breached this Agreement, our policies or standards, applicable laws, regulations, or third party rights, (iii) you have provided inaccurate, fraudulent, outdated or incomplete information during the Homebase Account registration, booking process or thereafter; (iv) Homebase becomes aware of or has received complaints about your performance or conduct, (v) you have repeatedly cancelled confirmed bookings without a valid reason, or (vii) Homebase believes in good faith that such action is reasonably necessary to protect the personal safety or property of Homebase, its Members, or third parties, or to prevent fraud or other illegal activity: </p>
                          <ul>
                              <li>refuse to surface any Member Content;</li>
                              <li>cancel any pending or confirmed bookings;</li>
                              <li>limit your access to or use of the Services;</li>
                              <li>temporarily or permanently revoke any special status associated with your Homebase Account;</li>
                              <li>temporarily or in case of severe or repeated offenses permanently suspend your Homebase Account and stop providing access to the Services.</li>
                          </ul>
                          <p>In case of non-material breaches and where appropriate, you will be given notice of any intended measure by Homebase and an opportunity to resolve the issue to Homebase's reasonable satisfaction.
                              <br /> 15.7 When this Agreement has been terminated, you are not entitled to a restoration of your Homebase Account or any of your Member Content. If your access to or use of the Services has been limited or your Homebase Account has been suspended or this Agreement has been terminated by us, you may not register a new Homebase Account or access and use the Services through an Homebase Account of another Member.
                              <br /> 15.8 Sections 3 and 12 to 21 of these Terms of Service shall survive any termination or expiration of this Agreement.</p>

                          <br />
                          <h3>16. Feedback</h3>
                          <br />

                          <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Service (&ldquo;Feedback&ldquo;). You may submit Feedback by emailing us or by other means of communication. Any Feedback you submit to us will be considered non-confidential and non-proprietary to you. By submitting Feedback to us, you grant us a non-exclusive, worldwide, royalty-free, irrevocable, sub-licensable, perpetual license to use and publish those ideas and materials for any purpose, without compensation to you.</p>

                          <br />
                          <h3>17. General Provisions</h3>
                          <br />
                          <p>17.1 Except as they may be supplemented by additional terms and conditions, policies, guidelines or standards, This Agreement constitutes the entire agreement between you and Homebase and govern your use of the Service, superseding any prior agreements between you and Homebase with respect to the Service.
                              <br /> 17.2 No joint venture, partnership, employment, or agency relationship exists between you and Homebase as a result of this Agreement or your use of the Services.
                              <br /> 17.3 These Terms of Service do not and are not intended to confer any rights or remedies upon any person other than the parties.
                              <br /> 17.4 These Terms of Service will be governed by the laws of the State of Delaware without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and Homebase agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within Alabama.
                              <br /> 17.5 The failure of Homebase to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties&rsquo; intentions as reflected in the provision, and the other provisions of this Agreement remain in full force and effect.
                              <br /> 17.6 You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
                              <br /> 17.7 You may not assign, sublet, license, or otherwise transfer or delegate your rights or obligations for the Accommodation under this Agreement or the Member Agreement without Homebase's prior written consent in our sole and unfettered discretion. Any assignment, subletting, licensing or transfer (whether by your voluntary act, operation of law, or otherwise), will be void, and we may elect to treat it as a non-curable breach of this Agreement. Homebase may at any time assign, encumber, delegate, or transfer, in whole or in part, without restriction, and you must look solely to our transferee for performance of our obligations relating to the period after the transfer. Your obligations under this Agreement will not otherwise be affected by any transfer.
                              <br /> 17.8 The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Service may also provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the Service.
                              <br /> 17.9 Unless specified otherwise, any notices or other communications to Members or Guests permitted or required under this Agreement, will be provided electronically and given by Homebase via email, Site notification, or messaging service (including SMS and WeChat). Requests and notices from us to any Guest will constitute notice to all Guests. Any notices from, consents by or actions taken by any Guest are deemed a notice from, consent by, or action of all Guests. All demonstrations, inspections and explanations made by us to one of the Guests will be binding on all Guests as if made to each of them.</p>

                          <br />
                          <h3>18. Special Notice for International Use; Export Controls</h3>
                          <br />

                          <p>Software available in connection with the Service and the transmission of applicable data, if any, is subject to United States export controls. No Software may be downloaded from the Service or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the Software is at your sole risk. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the Service, including as it concerns online conduct and acceptable content.</p>
                          <br />

                          <h3>19. Notice for California Users</h3>
                          <br />

                          <p>Under California Civil Code Section 1789.3, users of the Service from California are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210. You may contact us in writing at hello@renthomebase.com.</p>
                          <br />

                          <h3>20. Questions? Concerns? Suggestions?</h3>
                          <br />

                          <p>Please contact us at hello@renthomebase.com to report any violations of this Agreement or to pose any questions regarding this Terms of Service or the Service.</p>

                        </div>
                    </div>
                </div>
            </section>

           <Footer />
        </Fragment>
    )
}
const mapStateToProps = state => {
    return {
        logo: state.logo
    }
}

export default connect(mapStateToProps)(Terms);
